### ISSUE TITLE
Lora-Training brake my comfyui installation

### ISSUE THREAD

**Issue by kakachiex2** [LarryJane491/Lora-Training-in-Comfy#10]
I can't use comfyui this is what I get after installing your custom node:
I have comfyui portable version on windows.

K:\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-02-03 05:51:49.944061
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: K:\ComfyUI\python_embeded\python.exe
** Log path: K:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: K:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.1 seconds: K:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "K:\ComfyUI\ComfyUI\main.py", line 76, in <module>
    import execution
  File "K:\ComfyUI\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "K:\ComfyUI\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "K:\ComfyUI\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "K:\ComfyUI\ComfyUI\comfy\sd.py", line 3, in <module>
    from comfy import model_management
  File "K:\ComfyUI\ComfyUI\comfy\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\ComfyUI\comfy\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ComfyUI\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "K:\ComfyUI\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

K:\ComfyUI>pause
Press any key to continue . . .

**Comment by LarryJane491** [comment]
Don't worry, it's not broken. It just can't be accessed because it can't find CUDA. It's like the door is locked ^^.

I'll let you read the main page for Troubleshooting. Basically, you have to go to Pytorch and find the code line to install Torch with CUDA, then install that.

But you have to do it in the right folder. Since you have the portable version, it's a bit of a hassle. I'll copy-paste my comment from another issue:


> When running the portable version, we can't install packages easily because we need to install pip first. The good thing is the developer of the one-click install did almost all the work. The bad thing is... they stopped midway x). They added everything to install pip BUT didn't add pip.
> 
> Go in the python_embeded folder. Open a command prompt here (if you don't know how: click on the path, erase it all, type cmd and press Enter).
> 
> In the folder, do you see "get-pip.py"? It's a file to install pip inside the embedded python. In order to do that: type python get-pip.py in the command prompt and press Enter. This launches the download of pip.
> 
> After the download, type this in the prompt: .\Scripts\pip install -r [WITH A SPACE AFTER -r and don't press Enter yet!]
> 
> After this, go in the Lora-Training-in-Comfy folder. Grab the requirements file (requirements_win.txt if you're on windows) and drag it in the command prompt. This will write that file path in the prompt, after the -r. Again, there should be a space between the r and the path. Press Enter now. This installs the requirements INSIDE the embedded Python.
> 
> Go to https://pytorch.org/. On this website you'll see an Install Pytorch section, where you have several options (for OS, for for Pytorch Build, ...). Select the right options for your situation. If you have a RTX GPU, you must choose CUDA 12.1. This section gives you a line of code. Copy it.
> 
> Go back to the command prompt, type .\Scripts\ then paste the code the site gave you. In my case the final code looks like this: .\Scripts\pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121.
> 
> Then press Enter. It launches yet another download.


Once you manage to install torch with CUDA, ComfyUI will restart. If this doesn't work, you can try updating it, it should reinstall dependencies.

Honestly though, my advice is to download the "default" version of ComfyUI, not the one-click install.

https://www.reddit.com/r/comfyui/comments/1995whb/guide_learn_to_deal_with_python_programs/

If you follow this guide, you'll have a fresh install of ComfyUI where you control dependencies easily.

**Comment by kakachiex2** [comment]
You process work after updating dependencies with comfyui update dependencies.

**Comment by kakachiex2** [comment]
Thanks
