### ISSUE TITLE
Python not found

### ISSUE THREAD

**Issue by HedStudio** [LarryJane491/Lora-Training-in-Comfy#43]
basically the training not even start because it says that it can't find python i'm using latest version of comfy and nothing else gives me problem.
![cmd_BBIM6SXhiC](https://github.com/LarryJane491/Lora-Training-in-Comfy/assets/165191982/95d7a972-cea7-4e05-ae7e-8c0482fdec08)

**Comment by Samohtssetse** [comment]
HedStudio. I have this issue. How did you resolve?
